name: WMFGC
main: muqsit\wilderness\Wilderness
api: 3.0.0
version: 1.0.0

commands:
  wilderness:
    aliases: ["wild"]
    permission: wilderness.command

permissions:
  wilderness:
    default: false
    childrern:
      wilderness.command:
        default: op
